export type Pokemon = {
  id: number;
  name: string;
  image: string;
  stats: BaseStat[];
  types: Poketype[];
};
// Generated by https://quicktype.io
// Generated by https://quicktype.io
// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface BaseStat {
  base_stat: number;
  effort: number;
  stat: Stat;
}

export interface Stat {
  name: string;
  url: string;
}
// Generated by https://quicktype.io

export interface Poketype {
  slot: number;
  type: Type;
}

export interface Type {
  name: string;
  url: string;
}
